import {
  AreaChartOutlined,
  PieChartOutlined,
  BarChartOutlined,
  DotChartOutlined,
  LineChartOutlined,
  QqOutlined,
  WechatOutlined,
  AccountBookOutlined,
  AimOutlined,
  GlobalOutlined,
  LockOutlined,
  HddOutlined,
  SearchOutlined,
  TableOutlined,
  HomeOutlined,
  ReadOutlined,
  CommentOutlined,
  BarsOutlined,
  MessageOutlined,
  DatabaseOutlined,
  UserOutlined,
  ContactsOutlined,
  ClusterOutlined,
  PlusOutlined
} from "@ant-design/icons";

export default {
  areaChart: AreaChartOutlined,
  pieChart: PieChartOutlined,
  barChart: BarChartOutlined,
  dotChart: DotChartOutlined,
  lineChart: LineChartOutlined,
  qq: QqOutlined,
  wechat: WechatOutlined,
  accountBook: AccountBookOutlined,
  aim: AimOutlined,
  global: GlobalOutlined,
  lock: LockOutlined,
  hdd: HddOutlined,
  search: SearchOutlined,
  table: TableOutlined,
  home: HomeOutlined,
  read: ReadOutlined,
  comment: CommentOutlined,
  bars: BarsOutlined,
  message: MessageOutlined,
  database: DatabaseOutlined,
  user: UserOutlined,
  contacts: ContactsOutlined,
  cluster: ClusterOutlined,
  plus: PlusOutlined
};
